# Generated by Django 3.1.5 on 2021-01-18 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_game', '0003_coach'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coach',
        ),
    ]
