# Generated by Django 3.1.5 on 2021-01-18 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_game', '0006_coach'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(default=1.7)),
                ('no_games', models.IntegerField(default=1)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_game.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_game.user')),
            ],
        ),
    ]
