# Generated by Django 3.1.5 on 2021-01-18 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_game', '0007_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_game.team')),
            ],
        ),
        migrations.CreateModel(
            name='GameTeamScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_game.game')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_game.team')),
            ],
        ),
    ]
