# Generated by Django 3.1.5 on 2021-01-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_game', '0008_game_gameteamscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameteamscore',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
