# Generated by Django 3.1.5 on 2021-01-18 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_game', '0009_gameteamscore_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerGameScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_game.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_game.player')),
            ],
        ),
    ]
