# Generated by Django 3.1.5 on 2021-01-19 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_game', '0019_auto_20210119_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameteamscore',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_score', to='api_game.game'),
        ),
    ]
