# Generated by Django 3.1.5 on 2021-01-19 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_game', '0020_auto_20210119_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameteamscore',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_scores', to='api_game.team'),
        ),
    ]
