# Generated by Django 3.1.5 on 2021-01-19 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_game', '0021_auto_20210119_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='avg_score',
            field=models.FloatField(default=90),
        ),
        migrations.AddField(
            model_name='team',
            name='avg_score',
            field=models.FloatField(default=150),
        ),
    ]
